### ISSUE TITLE
小时流量统计任务失败

### ISSUE THREAD

**Issue by gosip443** [ProxyPanel/ProxyPanel#139]
**描述你遇到的bug**
简单的描述一下你遇到的bug

更新至master版本后，小时流量统计任务失败
2021-01-27 05:00:03] production.ERROR: Add [u] to fillable property to allow mass assignment on [App\Models\NodeHourlyDataFlow]. {"exception":"[object] (Illuminate\\Database\\Eloquent\\MassAssignmentException(code: 0): Add [u] to fillable property to allow mass assignment on [App\\Models\\NodeHourlyDataFlow]. at /www/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:356)

**如何复现你的BUG**
为方便找bug，请说明你bug产生的步骤

**截图**

**Comment by gosip443** [comment]
详细日志
[2021-01-27 05:00:03] production.ERROR: Add [u] to fillable property to allow mass assignment on [App\Models\NodeHourlyDataFlow]. {"exception":"[object] (Illuminate\\Database\\Eloquent\\MassAssignmentException(code: 0): Add [u] to fillable property to allow mass assignment on [App\\Models\\NodeHourlyDataFlow]. at /www/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:356)
[stacktrace]
#0 /www/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(174): Illuminate\\Database\\Eloquent\\Model->fill(Array)
#1 /www/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(419): Illuminate\\Database\\Eloquent\\Model->__construct(Array)
#2 /www/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php(295): Illuminate\\Database\\Eloquent\\Model->newInstance(Array)
#3 /www/wwwroot/example.com/app/Console/Commands/NodeHourlyTrafficStatistics.php(39): Illuminate\\Database\\Eloquent\\Relations\\HasOneOrMany->create(Array)
#4 /www/wwwroot/example.com/app/Console/Commands/NodeHourlyTrafficStatistics.php(19): App\\Console\\Commands\\NodeHourlyTrafficStatistics->statisticsByNode(Object(App\\Models\\Node))
#5 /www/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Console\\Commands\\NodeHourlyTrafficStatistics->handle()
#6 /www/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#7 /www/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#8 /www/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#9 /www/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#10 /www/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#11 /www/wwwroot/example.com/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#12 /www/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#13 /www/wwwroot/example.com/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /www/wwwroot/example.com/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\NodeHourlyTrafficStatistics), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /www/wwwroot/example.com/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /www/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /www/wwwroot/example.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /www/wwwroot/example.com/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 {main}
"}
