### ISSUE TITLE
开启验证码后无法登录

### ISSUE THREAD

**Issue by ACraft-Basement** [ProxyPanel/ProxyPanel#187]
**错误描述**
正确配置验证码后，无法登录。h和re均出现此问题。
![PIC](https://user-images.githubusercontent.com/70309328/125554839-f3fa76c1-aef0-4d01-a2ba-3798d76d2392.png)

**如何复现**
登录

**日志**
```
in_array() expects parameter 2 to be array, string given {"exception":"[object] (ErrorException(code: 0): in_array() expects parameter 2 to be array, string given at /www/wwwroot/domain/vendor/zbrettonye/no-captcha/src/NoCaptcha.php:214)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /www/wwwroot/domain/vendor/zbrettonye/no-captcha/src/NoCaptcha.php(214): in_array()
#2 /www/wwwroot/domain/vendor/zbrettonye/no-captcha/src/NoCaptchaServiceProvider.php(27): ZBrettonYe\\NoCaptcha\\NoCaptcha->verifyResponse()
#3 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(1358): ZBrettonYe\\NoCaptcha\\NoCaptchaServiceProvider->ZBrettonYe\\NoCaptcha\\{closure}()
#4 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(1392): Illuminate\\Validation\\Validator->callExtension()
#5 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(554): Illuminate\\Validation\\Validator->__call()
#6 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(377): Illuminate\\Validation\\Validator->validateAttribute()
#7 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(408): Illuminate\\Validation\\Validator->passes()
#8 /www/wwwroot/domain/app/Http/Controllers/AuthController.php(127): Illuminate\\Validation\\Validator->fails()
#9 /www/wwwroot/domain/app/Http/Controllers/AuthController.php(58): App\\Http\\Controllers\\AuthController->check_captcha()
#10 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\AuthController->login()
#11 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#12 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#13 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
#14 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
#15 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#16 /www/wwwroot/domain/app/Http/Middleware/isSecurity.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\isSecurity->handle()
#18 /www/wwwroot/domain/app/Http/Middleware/isMaintenance.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\isMaintenance->handle()
#20 /www/wwwroot/domain/app/Http/Middleware/Affiliate.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\Affiliate->handle()
#22 /www/wwwroot/domain/app/Http/Middleware/isForbidden.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\isForbidden->handle()
#24 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#26 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#28 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#30 /www/wwwroot/domain/app/Http/Middleware/SetLocale.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\SetLocale->handle()
#32 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#34 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#35 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#37 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#39 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then()
#41 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
#42 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()
#43 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
#44 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
#45 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#46 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#48 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#50 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#52 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#54 /www/wwwroot/domain/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#56 /www/wwwroot/domain/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#58 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()
#60 /www/wwwroot/domain/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#61 /www/wwwroot/domain/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle()
#62 {main}
```

**信息**
- 面板版本：Release 2.6.0
- Nginx 
- PHP 7.3

**Comment by ZBrettonYe** [comment]
更新你的composer 或者更新你的面板版本
